[tool.poetry]
name = "tg-bot"
version = "0.1.0"
description = ""
authors = ["Tretyak0ff <evgentretyakoff@gmail.com>"]
readme = "README.md"
packages = [{include = "tg_bot"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
