"""update User

Revision ID: 460b51e57c8c
Revises: 0c7ea5d19fc0
Create Date: 2023-06-11 23:28:00.952280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460b51e57c8c'
down_revision = '0c7ea5d19fc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
